### PR TITLE
Fixed broken readline behaviour using parameters module from ImageD11

### PR DESCRIPTION
**Pull request by jadball**
The readline behaviour was very broken when trying to read the parameters from the par files.
I used ImageD11's parameters module to fix this.

### CODE REVIEW

**Comment by jadball** [comment]
Note that this would require ImageD11 as an optional dependency to xfab, so I don't mind if these changes aren't merged. Can always just keep this script in-house for now.

**Comment by jonwright** [comment]
xfab is already a dependency for ImageD11, so maybe it would be easier to copy the ImageD11 code into xfab and then have ImageD11.parameters say something like "from xfab.parameters import *"?

Beware there are still some stupid bugs in the ImageD11 parameters code to be improved for reading too - I think it doesn't like blank lines etc. Long term this information could be stored in a more professional format that can be tracked to see what was done during analysis (e.g. hdf or NeXus or xml etc).

**Comment by jadball** [comment]
Not a bad idea.
Would it be as simple as copying parameters.py from ImageD11 into xfab, changing all references inside ImageD11 to `from xfab import parameters`, then rebuilding both?
If so, I can do those commits to both ImageD11 and xfab.

**Comment by jadball** [comment]
Note that other projects like S3DXRDS and TIMELESS would need updating too, so it'd require lots of pull requests...

**Comment by jadball** [comment]
Oh, never mind, I see what you mean.
Have ImageD11.parameters as an alias to xfab.parameters?
So the entire contents of the ImageD11.parameters file would just contain:
`from xfab.parameters import *`
Then we wouldn't need to update any other code.

**Comment by jonwright** [comment]
Sounds like it should work. Then within xfab you can remove ImageD11 but people using ImageD11 should not notice anything. Thanks!

**Comment by jadball** [comment]
Ok, it's been moved.
xfab is still not completely ImageD11-independent due to some scripts in scripts/ requiring other modules like columnfile and grain etc.

**Pull request merged**
