### PR TITLE
Lower atol in xfab.checks to allow for 32bit floats with xfab.tools

### PR DESCRIPTION
**Pull request by AxelHenningsson**
Lower atol in `xfab.checks` to allow for 32bit floats with `xfab.tools` without failing on orthonormality check.

### CODE REVIEW

**Comment by jonwright** [comment]
This paper claims 1 part in 1e7 precision for a unit cell .... https://doi.org/10.1107/S0108767305004496
So this lowered tolerance is probably not always the right thing to do?

**Comment by AxelHenningsson** [comment]
Seems we can at best to checks to see input dtypes and adapt tolerances accordingly. If people use lower precision than 64bit, then the tolerance of the checks must be lowered one way or another..

**Comment by AxelHenningsson** [comment]
Unfortunately casting back and forth between 64bit and 32bit will make an orientation matrix not pass a `np.allclose()`
```python
import numpy as np
u, _ = np.linalg.qr( np.random.standard_normal((3, 3)) )
u = np.asarray(u, np.float32)
u = np.asarray(u, float)
assert np.allcose(u.T.dot(u), np.eye(3,3))
```
This means that functions such as `xfab.tools.u_to_ubi()` and `xfab.tools.u_to_rod()` simply cannot handle anything but 64bit floats, or else they will fail in the `xfab.checks`. This reflects in some sense the fact that 32bit floats simply gives poor precision for rotation matrix operations.

**Review by jonwright — APPROVED** [review]
Looks good to me ...  thanks!

**Pull request merged**
